linters:
  enable:
    - bodyclose
    - cyclop
    - godox
    - godot
    - gofmt
    - misspell
    - sqlclosecheck
    - unconvert
    - whitespace
    - thelper
    - gofumpt
    - tparallel
    - unparam
    - wastedassign
    - revive
    - goheader

linters-settings:
  revive:
    enableAllRules: true
  goheader:
    values:
      const:
        GROUP: 'The yaff Authors'
        
      regexp:
        AUTHORS: '(Neil Hemming.*)'
    template-path: .header
  cyclop:
    # the maximal code complexity to report
    max-complexity: 16

issues:
  #https://github.com/golangci/golangci-lint/blob/a20748098fb3cb4b69f6b6ebb7809e7741122ef8/pkg/config/issues.go
  exclude-use-default: true
  include:
    - EXC0002
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015